### ISSUE TITLE
How to use this script?

### ISSUE THREAD

**Issue by Nriver** [SiriusXT/trilium-left-panel-auto-zoom#1]
I tried to execute it, didn't see anything happen.

**Comment by SiriusXT** [comment]
已经修正，请重新尝试。

**Comment by Nriver** [comment]
效果很棒。我要把这个加入到 https://github.com/Nriver/awesome-trilium 里面去

**Comment by hxchtiewei** [comment]
如果面板被隐藏了，能否实现鼠标移动到导航栏，自动显示面板。移开后再隐藏面板？

**Comment by SiriusXT** [comment]
> 如果面板被隐藏了，能否实现鼠标移动到导航栏，自动显示面板。移开后再隐藏面板？

改好了，隐藏时自动显示或隐藏

**Comment by hxchtiewei** [comment]
> > 如果面板被隐藏了，能否实现鼠标移动到导航栏，自动显示面板。移开后再隐藏面板？
> 
> 改好了，隐藏时自动显示或隐藏

感谢！对于我的小屏笔记本体验很好~
