### ISSUE TITLE
编辑块 按钮不见了

### ISSUE THREAD

**Issue by Nriver** [SiriusXT/trilium-left-panel-auto-zoom#2]
就是在行左边的那个按钮，可以修改标题2，标题3的。在触发了一次这个js之后，按钮就看不到了。得ctrl+r刷新一下才会出来。

**Comment by SiriusXT** [comment]
怎么复现这个bug，
该脚本确实会在缩放时隐藏编辑块按钮，这是为了防止缩放时按钮位置错乱，但是重新点击鼠标就出来了。

**Comment by Nriver** [comment]
我用了一个空的数据库测试了一遍
![GIF](https://user-images.githubusercontent.com/6752679/222873989-c07b1c2f-9e65-4081-bc22-7fb9decc3979.gif)

**Comment by SiriusXT** [comment]
找到原因了，已经修复。

**Comment by Nriver** [comment]
可以了
